author = 'Oxalin'
country_code = 'GB'
description = "The Arun Valley Line between Crawley and Arundel"
display_name = 'Arun_Valley_Line'
doc_files = [ 'Arun_Valley_Line.md' ]
factual = true
img_files = [ 'Arun_Valley_Line.bmp' ]
name = 'Arun_Valley_Line'
release_date = '2026-02-26'
rly_file = 'Arun_Valley_Line.rly'
ssn_files = [ 'Arun_Valley_Line_Initial_Session.ssn' ]
ttb_files = [ 'Arun_Valley_Line_2026-03-04.ttb' ]
version = '1.0.0'
